### PR TITLE
Finish content navigation!

### PR DESCRIPTION
**Pull request by axiomista**
Goal here is to make the modal's content fully **navigable** with arrows.

Suggestions and additions welcome! Keep committing~

### CODE REVIEW

**Comment by axiomista** [comment]
@NorthwestGreenChemistry/givecamp2018: 
- Anyone know how to cleanly/easily make that form `Submit` button center-aligned or right-aligned? I haven't read the json schema form docs yet.
- I want `navPrev` and `navNext` to also save the form data, but I will have to trigger the form submit to do that so I didn't yet. Feel free to do it first if it sounds simple ^_~

**Comment by axiomista** [comment]
@sjgllghr Agree, they'll look way better with space between them! I don't wanna do it in a hacky way is all so I need to look it up (I am *really* bad at front-end work). Tried with like `float` and/or `text-align` and I couldn't make it work. 

Anyone know what frameworks are we using to style the front-end that could be overriding that? I can just use their built-in way to do it if I can figure out what they are.

**Comment by halfnibble** [comment]
How do you feel about using Material UI buttons? I made a couple changes.
The best way to style, based on my 3 days of experience, is to add a `className={styles.someClass}` attribute to the tag. Then in Prism.css, make a `.someClass` CSS styling.

**Comment by axiomista** [comment]
Thanks @halfnibble! That's how I've been styling but I'm getting hit by style overrides inside either the form or the modal...

**Pull request merged**
